CREATE TABLE Alunos 
(
	ID_ALUNO INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(200) NOT NULL, 
	DATA_NASCIMENTO DATE NOT NULL,
	SEXO VARCHAR(1) NULL, --M para Masculino ou F para Feminino
	DATA_CADASTRO DATETIME NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL,
	CONSTRAINT FK_Alunos FOREIGN KEY (ID_ALUNO) REFERENCES Alunos (ID_ALUNO),
	CONSTRAINT FK_Tumas FOREIGN KEY (ID_ALUNO) REFERENCES Turmas (ID_TURMA)
);

DROP TABLE Alunos;

CREATE TABLE Situacao
(
	ID_SITUACAO INT PRIMARY KEY NOT NULL,
	SITUACAO VARCHAR(25) NOT NULL,
	DATA_CADASTRO DATETIME,
	LOGIN_CADASTRO VARCHAR(15)
);

CREATE TABLE Cursos
(
	ID_CURSO INT PRIMARY KEY NOT NULL,
	NOME_CURSO VARCHAR(200) NOT NULL,
	DATA_CADASTRO DATETIME NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL
);

CREATE TABLE Turmas 
(
	ID_TURMA INT PRIMARY KEY NOT NULL,
	ID_ALUNO INT NOT NULL,
	ID_CURSO INT NOT NULL,
	VALOR_TURMA NUMERIC(15,2) NOT NULL,
	DESCONTO NUMERIC(3,2) NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_TERMINO DATE,
	DATA_CADASTRO DATETIME NOT NULL,
	LOGIN_CADASTRO VARCHAR(15)
);

CREATE TABLE Registro_Presenca 
(
	ID_TURMA INT NOT NULL,
	ID_ALUNO INT NOT NULL,
	ID_SITUACAO INT NOT NULL,
	DATA_PRESENCA DATE NOT NULL,
	DATA_CADASTRO DATE NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL
);

/*
DROP TABLE  Turmas;
DROP TABLE  Situacao;
DROP TABLE  Registro_Presenca;
DROP TABLE  Cursos;
DROP TABLE  Alunos;
*/