INSERT INTO dbo.Alunos
(ID_ALUNO, NOME, DATA_NASCIMENTO, SEXO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES 
(2, 'Alessndro Henrique Peres Porfirio', '1989/10/04', 'M', '2022/10/26 06:50:00', 'JOY')

SELECT * FROM dbo.Alunos

INSERT INTO dbo.Cursos 
(ID_CURSO, NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES
(1, 'VBA I', '2019/11/02 06:52:00', 'JOY')

SELECT * FROM dbo.Cursos

INSERT INTO dbo.Situacao
(ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES
(1, 'Presença confirmada', '2019/11/02 06:53:00', 'JOY')

INSERT INTO dbo.Situacao
(ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES
(2, 'Ausente Sem Justificativa', '2019/11/02 06:53:00', 'JOY')

INSERT INTO dbo.Situacao
(ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES
(3, 'Ausente Com Justificativa', '2019/11/02 06:53:00', 'JOY')

SELECT * FROM dbo.Situacao